### ISSUE TITLE
Error with boolean

### ISSUE THREAD

**Issue by eldoy** [fugroup/hangersteak#1]
(node:76975) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at module.exports (/Users/vidar/src/microservices/lib/wpay/server/node_modules/hangersteak/lib/hangersteak.js:48:25)
    at Web.request (/Users/vidar/src/microservices/lib/wpay/server/node_modules/sirloin/lib/web.js:20:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:76975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:76975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by eldoy** [comment]
Happens when we try to get a route that doesn't exist e.g. GET / when / hasn't been defined.

**Comment by eldoy** [comment]
Should maybe be moved to Sirloin?

**Comment by eldoy** [comment]
Fixed in Sirloin
